
import enum

import commands as com

instruction_num_of_arguments = {
0:("BREAK","PUSHFRAME","CREATEFRAME","RETURN","POPFRAME", "CLEARS", "ADDS", "SUBS", "MULS", "IDIVS", "LTS", "GTS", "EQS", "ANDS", "ORS", "NOTS", "INT2CHARS", "STRI2INTS"),
1:("POPS","EXIT", "CALL","DEFVAR","LABEL","PUSHS","JUMP",  "WRITE","DPRINT", "JUMPIFEQS", "JUMPIFNEQS"),
2:("INT2CHAR","NOT", "MOVE","STRLEN","READ","TYPE","INT2FLOAT", "FLOAT2INT"),
3:("GETCHAR", "IDIV","ADD","MUL","CONCAT","JUMPIFEQ","LT","SUB","SETCHAR","GT","JUMPIFNEQ","OR","EQ","AND","STRI2INT", "DIV")
}   

instruction_formats ={
    "JUMPIFNEQS" : ["LABEL",None,None],
    "SETCHAR"    :["VAR","SYM","SYM"],
    "JUMPIFEQS" : ["LABEL",None,None],
    "GTS"  : [None,None,None],
    "FLOAT2INT" :["VAR", "SYM", None],
    "INT2FLOAT" :["VAR","SYM", None],
    "STRLEN"   :["VAR", "SYM",None],
    "TYPE"     :["VAR","SYM", None],  
    "SUB"    :["VAR", "SYM","SYM"],
    "EXIT"    :["SYM", None,None],
    "MUL"   :["VAR","SYM","SYM"],
    "LTS"  : [None,None,None],
    "IDIVS"  : [None,None,None],
    "MULS" : [None,None,None],
    "SUBS" : [None,None,None],
    "PUSHFRAME"  :[None,None, None],
    "ADDS" : [None, None,None],
    "JUMPIFEQ"   :["VAR","SYM", "SYM"],
    "AND"     :["VAR", "SYM","SYM"],
    "LABEL" :["LABEL",None, None],
    "JUMP"    :["LABEL",None, None],
    "JUMPIFNEQ" :["VAR","SYM","SYM"],
    "OR"        :["VAR","SYM", "SYM"],
    "READ"     :["VAR","TYPE", None],
    "WRITE"    :["SYM",None, None],
    "STRI2INTS": [None,None,None],
    "GETCHAR"   :["VAR", "SYM","SYM"],
    "CREATEFRAME":[None, None,None],
    "POPFRAME" :[None,None, None],
    "INT2CHAR":["VAR","SYM", None],
    "MOVE"     :["VAR","SYM", None],
    "NOT"      :["VAR", "SYM",None],
    "CLEARS" :[None, None, None],
    "PUSHS"    :["SYM", None,None],
    "DPRINT"   :["SYM",None, None],
    "DIV"      :["VAR", "SYM", "SYM"],
    "LT"      :["VAR", "SYM","SYM"],
    "INT2CHARS" : [None,None,None],
    "ADD"      :["VAR","SYM", "SYM"],     
    "IDIV"    :["VAR","SYM","SYM"],
    "NOTS" : [None,None,None],
    "ORS" : [None,None,None],
    "STRI2INT"  :["VAR","SYM","SYM"],
    "CONCAT"  :["VAR","SYM", "SYM"],
    "GT"      :["VAR","SYM", "SYM"],
    "EQ"      :["VAR","SYM","SYM"],
    "RETURN"  :[None,None,None],
    "BREAK"    :[None,None,None],
    "DEFVAR"   :["VAR", None, None],
    "POPS"   :["VAR", None, None],
    "CALL"     :["LABEL",None,None],
    "ANDS" : [None,None,None],
    "EQS": [None,None,None],
}


calling_func = {
    "EQS"        :com.ExecuteCommands().EQS,
    "JUMPIFNEQS" :com.ExecuteCommands().JUMPIFNEQS,
    "JUMPIFEQS"  :com.ExecuteCommands().JUMPIFEQS,
    "GTS"        :com.ExecuteCommands().GTS,
    "FLOAT2INT"  :com.ExecuteCommands().FLOAT2INT,
    "INT2FLOAT"  :com.ExecuteCommands().INT2FLOAT,
    "STRLEN"     :com.ExecuteCommands().STRLEN,
    "TYPE"       :com.ExecuteCommands().TYPE,
    "SUB"        :com.ExecuteCommands().SUB,
    "EXIT"       :com.ExecuteCommands().EXIT,
    "MUL"        :com.ExecuteCommands().MUL,
    "LTS"        :com.ExecuteCommands().LTS,
    "IDIVS"      :com.ExecuteCommands().IDIVS,
    "MULS"       :com.ExecuteCommands().MULS,
    "SUBS"       :com.ExecuteCommands().SUBS,
    "PUSHFRAME"  :com.ExecuteCommands().PUSHFRAME,
    "ADDS"       :com.ExecuteCommands().ADDS,
    "JUMPIFEQ"   :com.ExecuteCommands().JUMPIFEQ,
    "AND"        :com.ExecuteCommands().AND,
    "JUMP"       :com.ExecuteCommands().JUMP,
    "JUMPIFNEQ"  :com.ExecuteCommands().JUMPIFNEQ,
    "OR"         :com.ExecuteCommands().OR,
    "READ"       :com.ExecuteCommands().READ,
    "WRITE"      :com.ExecuteCommands().WRITE,
    "STRI2INTS"  :com.ExecuteCommands().STRI2INTS,
    "GETCHAR"    :com.ExecuteCommands().GETCHAR,
    "CREATEFRAME":com.ExecuteCommands().CREATEFRAME,
    "POPFRAME"   :com.ExecuteCommands().POPFRAME,
    "INT2CHAR"   :com.ExecuteCommands().INT2CHAR,
    "MOVE"       :com.ExecuteCommands().MOVE,
    "NOT"        :com.ExecuteCommands().NOT,
    "CLEARS"     :com.ExecuteCommands().CLEARS,
    "PUSHS"      :com.ExecuteCommands().PUSHS,
    "DPRINT"     :com.ExecuteCommands().DPRINT,
    "DIV"        :com.ExecuteCommands().DIV,
    "LT"         :com.ExecuteCommands().LT,
    "INT2CHARS"  :com.ExecuteCommands().INT2CHARS,
    "ADD"        :com.ExecuteCommands().ADD,
    "IDIV"       :com.ExecuteCommands().IDIV,
    "NOTS"       :com.ExecuteCommands().NOTS,
    "ORS"        :com.ExecuteCommands().ORS,
    "STRI2INT"   :com.ExecuteCommands().STR2INT,
    "CONCAT"     :com.ExecuteCommands().CONCAT,
    "GT"         :com.ExecuteCommands().GT,
    "EQ"         :com.ExecuteCommands().EQ,
    "RETURN"     :com.ExecuteCommands().RETURN,
    "BREAK"      :com.ExecuteCommands().BREAK,
    "DEFVAR"     :com.ExecuteCommands().DEFVAR,
    "POPS"       :com.ExecuteCommands().POPS,
    "CALL"       :com.ExecuteCommands().CALL,
    "ANDS"       :com.ExecuteCommands().ANDS,
    "SETCHAR"    :com.ExecuteCommands().SETCHAR
}