#!/usr/bin/env bash

export POSIXLY_CORRECT=yes

#       autor:  xkaska01    datum:  17.3.2022
#       VUT FIT - IOS project 1
#######################################################
#       regex and variables
#######################################################

valid_date='^[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]\b'
valid_gender='^[M|Z]\b'
valid_s_flag_argument='^[0-9]+\b$'

exist_file=0
command_used=0
flag_a_used=0
flag_b_used=0
flag_g_used=0
flag_s_used=0

DEFAULT_DEVIDERS_VALUES=(100000 10000 500 10000 100000 100 1000 10000)

#######################################################
#                   function declaration
#######################################################
date_validation()#function to check switches -a and -b date validatity
{
  if date -d "$1" >/dev/null 2>&1; then
      true
    else
      false
  fi
}

ERROR_CALL()#if there is error input, print error message and shut down the script
{
  echo "${1}" >"/dev/stderr"
  exit 1
}

print_help()#function, that print help if -h is given
{
                echo "corona [-h]"
                echo "corona [FILTERS] [COMMAND] [LOG [LOG2 [...]]"
                echo ""
                echo " FILTERS : "
                echo ""
                echo "-a [YYYY-MM-DD] "
                echo "-g [M\Z]"
                echo "-b [YYYY-MM-DD]   "
                echo "-s [NUMBER]"
                echo ""
                echo " FUNCTIONS : "
                echo ""
                echo "infected - vypise pocet nakazenych "
                echo "merge - slouci nekolik souboru se zaznamy do jednoho "
                echo "gender - vypise pocet nakazenych pro jednotliva pohlavi "
                echo "age - vypise statistiku nakazanych osob dle veku"
                echo "daily - vypise statistiku nakazanych osob pro jednotlive dny "
                echo "monthly - vypise statistiku nakazanych osob pro jednotlive mesice"
                echo "yearly - vypise statistiku nakazanych osob pro jednotlive roky "
                echo "countries - vypise statistiku nakazanych osob pro jednotlive zeme"
                echo "districts - vypise statistiku nakazanych osob pro jednotlive okresy "
                echo "regions - vypise statistiku nakazanych osob pro jednotlive kraje "
                exit 0
}

function_infected()#function, that counts every non blank row without head -> every infected person
{
OUTPUT_DATA=$(echo "$input_file" | awk '{if($1 !~ /^[[:space:]]*$/){ counter+=1 }}END{print int(counter)}')
}

function_merge()#function, that merges two or more files into one file with one head and exit 0
{
OUTPUT_DATA=$(echo "$input_file" | awk 'BEGIN{print "id,datum,vek,pohlavi,kraj_nuts_kod,okres_lau_kod,nakaza_v_zahranici,nakaza_zeme_csu_kod,reportovano_khs"}{print $0} ')
echo "$OUTPUT_DATA"
exit 0
}

function_gender()#function, that counts how many men and women are infected, if gender is not mentioned, prints none
{
OUTPUT_DATA=$(echo "$input_file" | awk -F ',' '{if($1 !~ /^[[:space:]]*$/){ if ( $4 ~ /^[/s/d M]+$/) { OUTPUT_DATA[0]+=1; } else if ( $4 ~ /^[s/d/ Z]+$/ ){ OUTPUT_DATA[1]+=1; } else if ($4 == "") {OUTPUT_DATA[3]+=1 } }}END {print "M: " int(OUTPUT_DATA[0]); print "Z: "int(OUTPUT_DATA[1]); if(OUTPUT_DATA[3]){print "None: " OUTPUT_DATA[3];}}')
S_DEFAULT_VALUE=${DEFAULT_DEVIDERS_VALUES[0]}
}

function_age()#functin, that counts how many people of specific age range were infected, if the age is not mentioned, prints none
{
OUTPUT_DATA=$(echo "$input_file" | awk -F ','   '{if($1 !~ /^[[:space:]]*$/){ if( $3 >= 0 && $3 <= 5 ) { OUTPUT_DATA[0]+=1; }
                                                 else if ( $3 >= 6 && $3 <= 15 ) { OUTPUT_DATA[1]+=1; }
                                                 else if ( $3 >= 16 && $3 <= 25 ) { OUTPUT_DATA[2]+=1; }
                                                 else if ( $3 >= 26 && $3 <= 35 ) { OUTPUT_DATA[3]+=1; }
                                                 else if ( $3 >= 36 && $3 <= 45 ) { OUTPUT_DATA[4]+=1; }
                                                 else if ( $3 >= 46 && $3 <= 55 ) { OUTPUT_DATA[5]+=1; }
                                                 else if ( $3 >= 56 && $3 <= 65 ) { OUTPUT_DATA[6]+=1; }
                                                 else if ( $3 >= 66 && $3 <= 75 ) { OUTPUT_DATA[7]+=1; }
                                                 else if ( $3 >= 76 && $3 <= 85 ) { OUTPUT_DATA[8]+=1; }
                                                 else if ( $3 >= 86 && $3 <= 95 ) { OUTPUT_DATA[9]+=1; }
                                                 else if ( $3 >= 96 && $3 <= 105 ) { OUTPUT_DATA[10]+=1; }
                                                 else if ( $3 > 105 ) { OUTPUT_DATA[11]+=1; }
                                                 else {OUTPUT_DATA[12]+=1 }}

                                                } END {
                                                  print "0-5   : " int(OUTPUT_DATA[0]);
                                                  print "6-15  : " int(OUTPUT_DATA[1]);
                                                  print "16-25 : " int(OUTPUT_DATA[2]);
                                                  print "26-35 : " int(OUTPUT_DATA[3]);
                                                  print "36-45 : " int(OUTPUT_DATA[4]);
                                                  print "46-55 : " int(OUTPUT_DATA[5]);
                                                  print "56-65 : " int(OUTPUT_DATA[6]);
                                                  print "66-75 : " int(OUTPUT_DATA[7]);
                                                  print "76-85 : " int(OUTPUT_DATA[8]);
                                                  print "86-95 : " int(OUTPUT_DATA[9]);
                                                  print "96-105: " int(OUTPUT_DATA[10]);
                                                  print ">105  : " int(OUTPUT_DATA[11]);
                                                  if( OUTPUT_DATA[12] ) {print "None  : " OUTPUT_DATA[12]}
                                                 }
                                                ')
S_DEFAULT_VALUE=${DEFAULT_DEVIDERS_VALUES[1]}
}
function_daily()#function, that counts number of infected people daily
{
OUTPUT_DATA=$(echo "$input_file" | awk -F ',' '{ if($1 !~ /^[[:space:]]*$/) {if($2 == ""){counter+=1} else{DAY[$2]++}}} END {for (i in DAY) {print i": " DAY[i]}; if(counter){print "None: " counter }}' | sort)
S_DEFAULT_VALUE=${DEFAULT_DEVIDERS_VALUES[2]}
}

function_monthly()#function, that counts number of infected people monthly
{
OUTPUT_DATA=$(echo "$input_file" | awk -F ',' '{if($1 !~ /^[[:space:]]*$/) {if( $2 == ""){counter+=1}else{MONTH[substr($2,1,7)]++}}}END {for (i in MONTH) {print i": "MONTH[i]}; if(counter){print "None: "counter}}' | sort)
S_DEFAULT_VALUE=${DEFAULT_DEVIDERS_VALUES[3]}
}

function_yearly()#function, that counts number of infected people yearly
{
OUTPUT_DATA=$(echo "$input_file" | awk -F ',' '{if($1 !~ /^[[:space:]]*$/) {if( $2 == "" ){counter+=1}else{YEAR[substr($2,1,4)]++}}} END {for (i in YEAR) {print i": "YEAR[i] }; if(counter){print "None: "counter}}' | sort)
S_DEFAULT_VALUE=${DEFAULT_DEVIDERS_VALUES[4]}
}

function_countries()#function, that counts number of infected people in every country
{
OUTPUT_DATA=$(echo "$input_file" | awk -F ',' '{if($1 !~ /^[[:space:]]*$/ && $8 != "" && $8 !="CZ"){COUNTRY[$8]++}}END{for (i in COUNTRY) {print i": "COUNTRY[i] ""}}' | sort)
S_DEFAULT_VALUE=${DEFAULT_DEVIDERS_VALUES[5]}
}

function_districts()#function, that counts number of infected people in every district
{
OUTPUT_DATA=$(echo "$input_file" | awk -F ',' '{if($1 !~ /^[[:space:]]*$/){if( $6 == ""){counter+=1}else{DISTRICT[$6]++}}} END {for (i in DISTRICT) {print i": "DISTRICT[i] ""}; if(counter){print "None: "counter}}' | sort)
S_DEFAULT_VALUE=${DEFAULT_DEVIDERS_VALUES[6]}
}

function_regions()#function, that counts number of infected people in every region
{
OUTPUT_DATA=$(echo "$input_file" | awk -F ',' '{if($1 !~ /^[[:space:]]*$/){if($5 == ""){counter+=1}else{REGION[$5]++} } }END{for (i in REGION) {print i": "REGION[i] ""}; if(counter){print "None: "counter}}' | sort)
S_DEFAULT_VALUE=${DEFAULT_DEVIDERS_VALUES[7]}
}

#######################################################
#             parsing arguments
#######################################################

while [ "$#" -gt 0 ]; do
  case "$1" in

  -h | --help)
      print_help
    ;;

  -a) if [ "$2" ];
    then
        if [ $flag_a_used -eq 0 ];
        then
              if [[ "$2" =~ $valid_date ]] && date_validation "$2";
               then
                  flag_date_after="$2"
                  flag_a_used=1
                  shift
                 else
                   ERROR_CALL "ERROR: datum neni validni nebo je zadane ve spatnem formatu"
              fi
                else
                    ERROR_CALL "ERROR: flag -a muze byt zadan maximalne jednou"
          fi
            else
                ERROR_CALL "ERROR: chybi parametr -a [YYYY-MM-DD]"
      fi
  ;;

  -b)if [ "$2" ];
    then
          if [ $flag_b_used -eq 0 ];
           then
               if [[ "$2" =~ $valid_date ]] && date_validation "$2";
               then
                   flag_date_before="$2"
                   flag_b_used=1
                   shift
                  else
                    ERROR_CALL "ERROR: datum neni validni nebo je zadane ve spatnem formatu"
              fi
              else
                ERROR_CALL "ERROR: flag -b muze byt zadan maximalne jednou"
           fi
           else
                ERROR_CALL "ERROR: chybi parametr -a [YYYY-MM-DD]"
    fi
  ;;

  -g) if [ "$2" ];
    then
          if [ $flag_g_used -eq 0 ];
          then
                if [[ "$2" =~ $valid_gender ]];
                then
                    gender_type="$2"
                    flag_g_used=1
                    shift
                    else
                      ERROR_CALL "ERROR: spatne zadany parametr Z/M"
                fi
                else
                  ERROR_CALL "ERROR: flag -g muze byt zadan maximalne jednou"
          fi

          else
            ERROR_CALL "ERROR: chybi parametr -g [M/Z]"
    fi
  ;;

  -s) if [ $flag_s_used -eq 0 ];
      then
          flag_s_used=1
          if [[ "$2" =~ $valid_s_flag_argument ]];
          then
            WIDTH=$2
            shift
          fi
      else
        ERROR_CALL "ERROR: flag -s muze byt zadan maximalne jednou"
      fi
  ;;

  merge | infected | gender | age | daily | monthly | yearly | countries | districts | regions)
  if [ $command_used -eq 0 ];
  then
    COMMAND="$1"
    command_used=1
    if [[ ("$COMMAND" == "merge"  ||  "$COMMAND" == "infected")  &&  $flag_s_used -eq 1 ]];
    then
        ERROR_CALL "ERROR: commandy infected a merge nesmmi byt pouzity s prepinacem -s"
    fi
    else
        ERROR_CALL "ERROR: Bylo zadano moc COMMANDU"
  fi
  ;;

  -?*)
    ERROR_CALL "ERROR: neznamy flag"
    ;;

  *.bz2)   if [ -f "$1" ];then
          input_file="$input_file$(bzcat "$1" | awk 'NR>1')"
          input_file="$input_file$(echo -e "\n\r")"
          exist_file=1
          else
            ERROR_CALL "ERROR: soubor $1 neexistuje"
          fi
    ;;

  *.gz)   if [ -f "$1" ];then
         input_file="$input_file$(zcat "$1" | awk 'NR>1')"
         input_file="$input_file$(echo -e "\n\r")"
         exist_file=1
                else
                  ERROR_CALL "ERROR: soubor $1 neexistuje"
         fi
    ;;

  *.csv)  if [ -f "$1" ];then

         input_file="$input_file$(cat "$1" | awk 'NR>1' )"
         input_file="$input_file$(echo -e "\n\r")"
         exist_file=1
         else
              ERROR_CALL "ERROR: soubor $1 neexistuje"

    fi
    ;;
  *)
    ERROR_CALL "ERROR: spatny format souboru, pouze .csv .csv.gz a csv.bz2 nebo neznamy commad"
;;
    esac
  shift
done

if [ $exist_file == 0 ];then
  input_file=$(cat | awk 'NR>1' )
fi

#######################################################
#         parsing "harder" files with white spaces
#######################################################

input_file=$(echo "$input_file" | awk -F ',' '{gsub(/ /,""); if( $0 !~ /^[[:space:]]*$/){print $0}}' | tr -d $'\r')

#######################################################
#        date validation
#######################################################

input_file=$(echo "$input_file" | awk -F ',' '{ ;MONTH=substr($2,6,2); DAY=substr($2,9,2); YEAR=substr($2,1,4);

        if((($2 ~ /^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$/ || ($2 ~ /^[[:space:]]*$/)) && int(MONTH) <= 12 ))
        {

                      if (( int(DAY) > 0 && int(DAY) <= 30 ) && (int(MONTH) == 4 ||  int(MONTH) == 6 || int(MONTH) == 9 || int(MONTH) == 11))
                      { print $0  }

                      else if (( int(MONTH) == 1 || int(MONTH) == 3 || int(MONTH) == 5 || int(MONTH) == 7 || int(MONTH) == 8 || int(MONTH) == 10 || int(MONTH) == 12 ) && (int(DAY) > 0 && int(DAY) <= 31 ))
                      {print $0 }

                      else if (int(MONTH) == 2 && ( int(DAY) > 0 &&  int(DAY) <= 29 ) && (  int(YEAR) % 4 == 0 && (int(YEAR) % 100 == 0 || int(YEAR) % 400 != 0)))
                      {print $0}

                      else if ((int(DAY) <= 28 && int(DAY) > 0) && int(MONTH) == 2 || $2 == "")
                      { print $0 }

                      else
                      {
                      BAD_DATE[$0]++
                      }
        }
       else
       {
      BAD_DATE[$0]++
       }
    }
    END{for(i in BAD_DATE) { print "Invalid date: " i > "/dev/stderr" }
}')

#######################################################
#         age validation
#######################################################

input_file=$(echo "$input_file" | awk -F ',' '{if ($3 == "" || $3 ~ /^[/s 0-9]+$/) { print $0 }else{ BAD_AGE[$0]++} }END{ for(i in BAD_AGE){print "Invalid age: " i > "/dev/stderr"} } ')

#######################################################
#         filtres if switch is given
#######################################################

if [ -n "$flag_date_after" ];
then
 input_file=$(echo "$input_file" | awk -F ',' -v date_after="$flag_date_after" '{if ( $2 >= date_after) {print $0}}')
fi

if [ -n "$flag_date_before" ];
then
  input_file=$(echo "$input_file" | awk -F ',' -v date_before="$flag_date_before" '{if ($2 <= date_before ){ print $0}}')
fi

if [ -n "$gender_type" ];
then
  input_file=$(echo "$input_file" | awk -F ',' -v gender="$gender_type" '{if ( $4 == gender ) {print $0 }}')
fi

#######################################################
#       function calling
#######################################################

case "$COMMAND" in
  infected)
    function_infected
    ;;
  merge)
    function_merge
    ;;
  gender)
    function_gender
    ;;
  age)
    function_age
    ;;
  daily)
    function_daily
    ;;
  monthly)
    function_monthly
    ;;
  yearly)
    function_yearly
    ;;
  countries)
    function_countries
    ;;
  districts)
    function_districts
    ;;
  regions)
    function_regions
    ;;
  *) function_merge
    exit 0
    ;;
esac

#######################################################
#          creating graphs if -s is given
#                      and
#          printing output
#######################################################

if [ $flag_s_used -eq 1 ];
then

  if [[ $WIDTH -ne 0 ]];
  then
    maximu_value=$(echo  "$OUTPUT_DATA" | awk -F ':' '{ if ( $2 > max ){ max=$2 }} END {print max}' )
    echo "$OUTPUT_DATA" | awk -F ':' -v max="$maximu_value" -v s_value="$WIDTH" '{printf ("%s: ", $1); for (i = 0; i < int(($2/max)*s_value);i++){printf("#")};printf("\n")} '
    exit 0

  else

    echo "$OUTPUT_DATA" | awk -F ':' -v com="$S_DEFAULT_VALUE" '{printf ("%s: ", $1); for (i = 0; i < int(($2/com)); i++){printf("#")};printf("\n")} '
    exit 0

  fi
  else

      echo "$OUTPUT_DATA"
      exit 0
fi

#######################################################
